### ISSUE TITLE
How to build without Android SDK?

### ISSUE THREAD

**Issue by smabie** [regb/scala-game-library#3]
Hi, I've been trying to build and publish-local SGL but it doesn't seem to be working. If I just do:
`sbt compile` I eventually get `com.android.support#support-v4;23.0.0: not found` as an error. Is there anyway I can build and publish the library without Android SDK support? 

Thanks!

**Comment by regb** [comment]
Hi,

You need to build the specific sub-projects that you need. For example, you can do `sbt coreJVM/compile` to build the core library for the JVM platform, and `sbt desktopAWT/compile` (or desktop/compile, depending on which commit you are at) for building the support for AWT on the JVM.

The current list of sub-projects are:
  * coreJVM, coreJS, coreNative (the core abstractions compiled for JVM, scalajs, and scala-native).
  * desktopAWT, depends on coreJVM and provide window and graphics with AWT.
  * desktopNative, depends on coreNative and use scala-native and OpenGL to build a native executable.
  * html5, depends on coreJS and use scala.js to generate a javascript game.
  * coreAndroid and android for the android platform.
  * jvmShared, some non-core utilities shared by all JVM-based platform

These projects are defined in the build.sbt and have their sources in the corresponding subdirectory.

I never tried to publish the project locally, but If you want to you should be able to publish the desktop support (probably the simpler to develop), you can use:
  `sbt desktopAWT/publishLocal`
You would also need the dependencies as they don't seem to be published:
  `sbt coreJVM/publishLocal` and `jvmShared/publishLocal`
Then you need to add all these dependencies on your own project.

A simpler solution would be to use direct sbt dependencies, there is an example in the `examples/snake` project (https://github.com/regb/scala-game-library/blob/master/examples/snake/build.sbt). It shows how you can depend on SGL if you have a local checkout of the code. You can use ProjectRef to build the reference to SGL sub-projects and then you define your own project with the dependencies that you need. To see it in action, try `sbt desktop/run` in the snake directory, and this will start a desktop version of the game (without compiling for other platforms).

**Comment by smabie** [comment]
Thanks!
